# Generated by Django 5.0.4 on 2024-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slugify(self.title)', unique=True),
            preserve_default=False,
        ),
    ]
